Tutorial_point/urls.py
from django.contrib import admin
from django.urls import path

from . import views
urlpatterns = [
    path("", views.index, name="home"),
    path("contact", views.contact_dtls, name="con"),
    path("registration", views.sign_up, name="signup"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path('course/<str:slug>', views.course_information, name="course"),
    # path('course', views.course_information, name="cou"),
    path('checkout/<str:slug>', views.checkout, name="checkout"),
    path('verify_payment', views.verify_payment, name="verifypayment"),



]

udemy/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
        path('admin/', admin.site.urls),
        path("",include('Tutorial_point.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tutorial_point/models.py
from django.db import models
from torch import mode


# Create your models here.


class user_signup(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=255)
    mobile = models.BigIntegerField()
    gender = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name


class course_dtls(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    price = models.IntegerField(null=False)
    discount = models.IntegerField(null=False)
    desc = models.CharField(max_length=200)

    image = models.ImageField(upload_to='image/')

    def __str__(self):
        return self.name


class video(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    s_no = models.IntegerField()
    course_name = models.ForeignKey(course_dtls, on_delete=models.CASCADE)
    video_id = models.CharField(max_length=200)
    is_preview = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class UserCourse(models.Model):
    user_name = models.ForeignKey(user_signup, on_delete=models.CASCADE)
    course_name = models.ForeignKey(course_dtls, on_delete=models.CASCADE)
    # date =

    def __str__(self):
        return self.user_name.first_name


class payment(models.Model):
    order_id = models.CharField(max_length=200)
    payment_id = models.CharField(max_length=200)
    user = models.ForeignKey(user_signup, on_delete=models.CASCADE)
    course = models.ForeignKey(course_dtls, on_delete=models.CASCADE)
    user_course = models.ForeignKey(
        UserCourse, null=True, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.order_id

class Refcode(models.Model):
    code = models.CharField(max_length=100)
    user_course = models.ForeignKey(course_dtls,on_delete=models.CASCADE)
    discount = models.IntegerField(default=0)

    def __str__(self):
        return self.code



class course_info(models.Model):
    desc =  models.CharField(max_length=500)
    course = models.ForeignKey(course_dtls,on_delete=models.CASCADE)

    class Meta:
        abstract = True
        
class learning(course_info):
    pass


class pre_req(course_info):
    pass

# class learning(course_info):
#     pass

Tutorial_point/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from time import time

from sympy import re

from . models import *
# Create your views here.
from django.contrib.auth.hashers import check_password, make_password
from django.views.decorators.csrf import csrf_exempt
import razorpay
from udemy.settings import *
client = razorpay.Client(auth=(key_id, secret_id))


def index(request):

    course_info = course_dtls.objects.all()

    return render(request, 'home.html', {'course_info': course_info})


def contact_dtls(request):
    return render(request, 'contact.html')


def sign_up(request):
    if request.method == "POST":
        fname = request.POST.get('first_name')
        lname = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        mobile = request.POST.get('mobile')
        gender = request.POST.get('gender')

        save_info = user_signup(first_name=fname, last_name=lname, email=email,
                                password=make_password(password), mobile=mobile, gender=gender)
        save_info.save()

        return HttpResponse("registration succsessfull")


def login(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            fetch_info = user_signup.objects.get(email=email)
            if(check_password(password, fetch_info.password)):

                # print("you have entered correct password")
                request.session['name'] = fetch_info.first_name
                request.session['email'] = fetch_info.email
                return redirect('home')

            else:
                return HttpResponse("please enter a valid password")

        except:
            return HttpResponse("please enter a valid email....")


def logout(request):

    request.session.clear()
    return redirect('home')


def course_information(request, slug):

    fetch_dtls = course_dtls.objects.get(slug=slug)
    s_no = request.GET.get('serial_no')
    videos = None
    if s_no is None:
        s_no = 1
    try:
        videos = video.objects.get(course_name=fetch_dtls, s_no=s_no)
        if videos.is_preview is False:
            if request.session.get('name') is None:
                return redirect('home')
            else:
                user_id = user_signup.objects.get(
                    email=request.session['email'])
                try:
                    user_course = UserCourse.objects.get(
                        user_name=user_id, course_name=fetch_dtls)
                    print(user_course)
                except:
                    return redirect('checkout', slug=fetch_dtls.slug)
    except:
        return redirect('home')

    return render(request, 'course_dtls.html', {'co_dtls': fetch_dtls, 'video': videos})


def checkout(request, slug):
    course = course_dtls.objects.get(slug=slug)
    user_id = user_signup.objects.get(email=request.session['email'])
    action = request.GET.get('action')
    coup = request.GET.get('coupon')

    error = None
    cpn_code_msg = None
    amount = None

    order_ids = None
    notes = None
    cpn_code = None
    if error is None:
        amount = int(course.price * ((100-course.discount) * 0.01)*100)

    if coup:
        try:
            cpn_code = Refcode.objects.get(course=course,code=coup)
            amount = int(course.price * ((100-cpn_code.discount) * 0.01)*100)
        except:
            cpn_code_msg = "invalid coupon code"

    if action == 'create_payment':

        currency = "INR"
        receipt = f'Tutorial_point-{int(time())}'
        notes = {
            'user': user_id.first_name,
            'email': user_id.email
        }
        data = {
            "amount": amount,
            "currency": currency,
            "receipt": receipt,
            "notes": notes
        }
        orders = client.order.create(data=data)
        # print(payment)
        order_ids = orders.get('id')
        payments = payment()
        payments.order_id = order_ids

        payments.user = user_id
        payments.course = course
        payments.save()
    if coup == "":
        cpn_code_msg = "please enter a coupon code"
    context = {
        'user_id': user_id,
        'course': course,
        'order_id': order_ids,
        'notes': notes,
        'cpn_code_msg': cpn_code_msg,
        'coup': cpn_code,
        'error': error


    }

    return render(request, 'checkout.html', context=context)


@csrf_exempt
def verify_payment(request):
    data = request.POST
    user_id = user_signup.objects.get(email=request.session['email'])

    payment_id = data['razorpay_payment_id']
    razor_order_id = data['razorpay_order_id']
    payments = payment.objects.get(order_id=razor_order_id)
    payments.payment_id = payment_id
    payments.status = True
    user_courses = UserCourse(
        user_name=payments.user, course_name=payments.course)
    user_courses.save()
    payments.user_course = user_courses
    payments.save()

    try:
        return redirect('home')
    except:
        return HttpResponse("successfull")

Tutorial_point/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>  {% block title %}{% endblock title %}   </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    
    <div class = "container">
        <nav class="navbar navbar-expand-lg bg-dark ">
  <div class="container-fluid">
    <a class="navbar-brand  text-light" href="#">{{request.session.name}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'con' %}">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu text-light" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light">My Course</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" >Search</button>
        </form>
        {% if request.session.email %}

        <form action="{% url 'logout' %}" method = "post">
          {% csrf_token %}
          <button class="btn btn-primary mx-3" type = "submit">Logout</button>
        </form>

        {% else %}
        <button class="btn btn-primary mx-2"  data-bs-toggle="modal" data-bs-target="#signup">SignUp</button>
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#login">Login</button>
        {% endif %}
      
    </div>
  </div>
</nav>
  {% comment %} modal for signup {% endcomment %}

    
<!-- Modal -->
<div class="modal fade" id="signup" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Sign Up</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <form action = "{% url 'signup' %}" method = "post" class="row g-3">
              {% csrf_token %}
  <div class="col-md-6">
    <label for="fname" class="form-label">First Name</label>
    <input type="text" name = "first_name" class="form-control" id="fname">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Last Name</label>
    <input type="text" name = "last_name" class="form-control" id="lname">
  </div>
    <div class="col-md-6">
    <label for="email" class="form-label">Email</label>
    <input type="email" name = "email" class="form-control" id="email">
  </div>
  <div class="col-md-6">
    <label for="password" class="form-label">Password</label>
    <input type="password" name = "password" class="form-control" id="password">
  </div>
  <div class="col-md-6">
    <label for="mobile" class="form-label">Mobile</label>
    <input type="number" name = "mobile" class="form-control" id="mobile">
  </div>
  <div class="col-md-6">
    <label for="gender" class="form-label">Gender</label>
    <br>
    
    <input type="radio"  name = "gender" id="gender" value = "male">Male
    <input type="radio"  name = "gender" id="gender" value = "female">Female
  </div>
  
  
  
  <div class="col-12">
   <center> <button type="submit" class="btn btn-primary">Sign in</button></center>
  </div>
</form>
      </div>
      
    </div>
  </div>
</div>

{% comment %} modal for sign in {% endcomment %}
<div class="modal fade" id="login" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method = "post" action = "{% url 'login' %}" class="row g-3">
          {% csrf_token %}
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label">Email</label>
    <input type="email" name = "email" class="form-control" id="inputEmail4">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Password</label>
    <input type="password" name = "password" class="form-control" id="inputPassword4">
  </div>

  <div class="col-12">
    <button type="submit" class="btn btn-primary">Sign in</button>
  </div>
</form>
      </div>
      
    </div>
  </div>
</div>




    </div>
    {% block content %}{% endblock content %}


  

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
  </body>
</html>

Tutorial_point/templates/checkout.html
{% extends 'base.html' %}
{% load discount_calc %}
{% block content %}

<div class="container my-3">

    <div>
       {% comment %} {% if order is not None %}
       {{order}}
       {% endif %} {% endcomment %}
    </div>
    <div class="row mx-auto">
        <div class="col">
            <div class="card mx-auto" style="width: 18rem;">
                <img src=" {{course.image.url}}" class="card-img-top" alt="..." height=200>
                <div class="card-body">

                    <h5 class="card-title">{{course.name}}</h5>
                    <p class="card-text">{{course.discount}}%
                        <br>
                        <del>  Rs.{{course.price}}</del>
                    </p>
                </div>
            </div>
        </div>
        <div class ="col">
            <h1>You have to pay : {{course.name}}</h1>

    
            
            <div>
                <div class="col my-3">
                    <h3>Apply Code: </h3>
                    {% if coup %}
                    <div class="alert alert-primary" role="alert">
                           
                            you got:  {{coup.discount}}%  discount
                    </div>
                    {% elif cpn_code_msg %}
                    <div class="alert alert-primary" role="alert">
                             {{cpn_code_msg}}
                    </div>

                    {% endif %}
                    <form action="" method = "get">
                        <input type="text" name="coupon" id="" placeholder = "enter your code">
                        <input type="submit" class = "btn btn-primary"value ="apply">
                    </form>
                    {% if coup %}
                
                      <h3>Rs.{% price_discount course.price coup.discount %}</h3>
            <a class="btn btn-success border" href="?action=create_payment&coupon={{coup.code}}">Continue to Payment</a> 
            {% else %}
             <h3>Rs.{% price_discount course.price course.discount %}</h3>
            <a class="btn btn-success border" href="?action=create_payment">Continue to Payment</a> 
             {% endif %}
                </div>

            </div>
             
            {% comment %} <button id="rzp-button1" class = "btn btn-success">Pay</button> {% endcomment %}
        </div>

        
    </div>
</div>


{% if order_id is not None %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_NEwAa8bvoxiG2T", // Enter the Key ID generated from the Dashboard
    "amount": "{{amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Udemy Corp",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "http://127.0.0.1:8000/verify_payment",
    "prefill": {
        "name": "{{user_id.first_name}}",
        "email": "{{user_id.email}}",
       
    },
    "notes": {
        "address": "{{notes}}"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);


rzp1.open();
</script>
{% endif %}



{% endblock content %}

Tutorial_point/templates/contact.html
{% extends 'base.html' %}

{% block title %}
  Contact
{% endblock title %}
{% block content %}
<h1>this is my Contact page</h1>
{% endblock content %}

Tutorial_point/templates/course_dtls.html
{% extends 'base.html' %}
{% load discount_calc %}
{% block content %}

    <div class="container my-3">
        <div class="row border my-2" >
            <div class="col my-3">
                <ul class="list-group">
                     {% is_enroll request course  as  enrolled %}
                            {% for vid in co_dtls.video_set.all  %}

                            
                                <li class="list-group-item {% if vid == video %} active-video {% endif %}"aria-current="true">
                                  <a href="?serial_no={{vid.s_no}}" class="{% if vid == video %} active-video-link {% endif %}{% if not enrolled and not vid.is_preview %}text-muted" style = "cursor: not-allowed; {% endif %}">{{vid}}</a>
                                </li>
                                                    
                            {% endfor %}
                </ul>
            </div>
            
            <div class="col-9">

                

                <iframe width="100%" height="315" src="https://www.youtube.com/embed/{{video.video_id}}" title="Learn Python from basic | Learn Python from scratch |" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe >
              

            </div>
        </div>
        <div class="row border">
            <div class="col">
                <h1>
                    Learning
                </h1>
                <ul>
                    {% for i in co_dtls.learning_set.all  %}
                <li> {{i.desc}}</li>
                {% endfor %}
                </ul>
               
            </div>
              
        </div>
        <div class="row border ">
        <div class="col">
                <h1>Pre Requ</h1>
           
                <ul>
                    {% for i in co_dtls.pre_req_set.all  %}
                <li> {{i.desc}}</li>
                {% endfor %}
                </ul>
               
            
        </div>
        </div>



    </div>

{% endblock content %}

Tutorial_point/templates/home.html
{% extends 'base.html' %}
{% load discount_calc %}
{% block title %}
    Home
{% endblock title %}
{% block content %}
<div class = "container">
    <div class="row my-3">
    {% for course in course_info %}

        <div class="card mx-3" style="width: 18rem;">
            <img src="{{course.image.url}}" class="card-img-top" alt="..." height = 150>
            <div class="card-body">
                <h5 class="card-title">{{course.name}}</h5>
                
                <p class="card-title">{{course.desc}}</p>
                <p class="card-text"> discount :{{course.discount}}%
                <p class="card-title">
                    <del>Rs.{{course.price}}</del></p>
                <h3 class="card-title">Rs.{% price_discount course.price  course.discount %}</h3>

        </div>
        <div class="card-footer p-2 ">
            <div class="col border-right d-md-flex justify-content-md-around gap-2">
                 
                        {% is_enroll request course  as  enrolled %}

                        {% if enrolled %}
                            <a href="course/{{course.slug}}" class="btn btn-primary btn-block">Start Course</a>

                        {% elif request.session.email %}

                        <a href="checkout/{{course.slug}}" class="btn btn-primary btn-block">Enroll Now</a>

                        <a href="course/{{course.slug}}" class="btn btn-primary btn-block">More</a>

                        {% else %}
                        <a  class="btn btn-primary btn-block" data-bs-target = "#login" data-bs-toggle = "modal">Enroll Now</a>
                        <a href="course/{{course.slug}}" class="btn btn-primary btn-block">More</a>
                        {% endif %}
             </div>                            
        </div>
        </div>
    
    {% endfor %}
    </div>

</div>

{% endblock content %}